// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnAHx11SH_Zj-sawFTgRvXHCKvOHOMotM',
    appId: '1:1020983670860:web:6cbb4b232bafcab0639ce9',
    messagingSenderId: '1020983670860',
    projectId: 'flutter-webrtc-fde0f',
    authDomain: 'flutter-webrtc-fde0f.firebaseapp.com',
    storageBucket: 'flutter-webrtc-fde0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8UjZT8yT6rxnQtp9z6qw22ye1L-O6HWY',
    appId: '1:1020983670860:android:a4b25e3db5bd4d90639ce9',
    messagingSenderId: '1020983670860',
    projectId: 'flutter-webrtc-fde0f',
    storageBucket: 'flutter-webrtc-fde0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1sJ3IpY6426M-7ulAUq0e-tyo8JBqtso',
    appId: '1:1020983670860:ios:6ffcc883811bc7ef639ce9',
    messagingSenderId: '1020983670860',
    projectId: 'flutter-webrtc-fde0f',
    storageBucket: 'flutter-webrtc-fde0f.appspot.com',
    iosBundleId: 'com.example.flutterWebrtcExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1sJ3IpY6426M-7ulAUq0e-tyo8JBqtso',
    appId: '1:1020983670860:ios:4f21bcfdb8710337639ce9',
    messagingSenderId: '1020983670860',
    projectId: 'flutter-webrtc-fde0f',
    storageBucket: 'flutter-webrtc-fde0f.appspot.com',
    iosBundleId: 'com.example.flutterWebrtcExample.RunnerTests',
  );
}
